.PHONY: help test lint format typecheck

help:
	@echo "Frontend"
	@echo "  make test"
	@echo "  make lint"
	@echo "  make typecheck"

test:
	@pnpm test

lint:
	@pnpm lint:check

format:
	@pnpm format:fix

typecheck:
	@pnpm typecheck
